BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        id: input_clear
        text: 'Clear'
        on_press: app.handle_clear()
    TextInput:
        id: input_name
        text: ''
    Button:
        id: greet_button
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: "Enter your name"
        color: (1, 1, 0, 1)
